remote_theme: streetturtle/jekyll-clean-dark
title: SNVMK
description: Страница SNVMK
email: sidzahroman@gmail.com
github-username: SNvMK
author: SNVMK
permalink: /:categories/:title
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - 
    scope:
      path: ""
    values:
      layout: "default"
show_downloads: true
github:
  zip_url: /snvmdb.zip
  tar_url: /snvmdb.tar.gz
lang: ru-RU
