theme: jekyll-theme-hacker
title: SNVMK
description: Страница SNVMK
author:
    name: SNVMK
    email: sidzahroman@gmail.com
permalink: /:categories/:title
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
show_downloads: true
github:
  zip_url: /snvmdb.zip
  tar_url: /snvmdb.tar.gz
lang: ru-RU
