theme: minima
minima:
  skin: dark
  social_links:
    github: SNvMK
    telegram: SNVMK
title: Страница СНВМК
author:
  name: SNVMK
  email: sidzahroman@gmail.com
header_pages:
  - https://discord.gg/n3xr8VbGw8
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /:categories/:title
  - 
    scope:
      path: ""
    values:
      layout: "default"
disqus:
  shortname: snvmk
show_downloads: true
github:
  zip_url: /snvmdb.zip
  tar_url: /snvmdb.tar.gz
lang: ru-RU
